apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-practice
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-practice
  template:
    metadata:
      labels:
        app: app-practice
    spec:
      containers:
      - name: app-practice
        image: entropypool/app-practice:latest
        imagePullPolicy: Always
        env:
        - name: ENV_ENVIRONMENT_TARGET
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.target
        - name: ENV_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_host
        - name: ENV_CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_port
        - name: ENV_CLUSTER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

---
apiVersion: v1
kind: Service
metadata:
  name: app-practice
  namespace: kube-system
spec:
  ports:
  - name: api
    port: 32759
    targetPort: 32759
  selector:
    app: app-practice
