apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: service-sample-npool-top-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: service-sample-npool
    k8s.kuboard.cn/workload: service-sample-npool
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-strip-service-sample-prefix@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http:
        paths:
          - path: /api/service-sample
            backend:
              serviceName: service-sample
              servicePort: 32759

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: service-sample-xpool-top-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: service-sample-xpool
    k8s.kuboard.cn/workload: service-sample-xpool
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-strip-service-sample-prefix@kubernetescrd

spec:
  rules:
    - host: api.xpool.top
      http:
        paths:
          - path: /api/service-sample
            backend:
              serviceName: service-sample
              servicePort: 32759

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-service-sample-prefix
  namespace: kube-system
spec:
  stripPrefix:
    prefixes:
      - /api/service-sample
